#!/bin/bash
# USAGE: dconf_load <filename>
# Load a .dconf file named like "org.my.app.dconf" into dconf

source dconf_functions.sh

DCONF_PATH="$(file_to_dconf_path $1)"
echo "Loading $1 to ${DCONF_PATH}..."
dconf load ${DCONF_PATH} < "$1"
