#!/bin/bash
secret-tool lookup local_user password > /dev/null # Force unlock first.
lssecret --secrets \
    | egrep 'Secret:' \
    | egrep -iv 'the meaning of life' \
    | cut -f2 \
    | sort \
    | uniq \
    | fzf \
    | xclip -in -selection clipboard \
    2>&1
