#!/bin/bash
#
# Source: https://github.com/junegunn/fzf/wiki/examples

PIDS=""
if [[ "$UID" != "0" ]]; then
    PIDS=$(ps -f -u $UID | sed 1d | fzf -m | awk '{print $2}')
else
    PIDS=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')
fi

if [[ -n "${PIDS}"  ]]
then
    echo "Killing PIDs: " ${PIDS} " with arguments [${@}]..."
    echo ${PIDS} | xargs kill "$@"
fi
