#!/bin/bash

source ps_functions.sh

EXCLUDE='fps|fpsk|fzf'

procs --pager disable --color disable \
    | egrep -vw ${EXCLUDE} \
    | fzf --multi --header-lines=2 --query=$1 --preview='print_cmd {}' --preview-window='bottom:3:wrap' \
    | extract_pid
