#!/bin/bash
# Select and kill processes
# Usage: fps [<query>] [<kill-args>...]

# Params ranges: https://stackoverflow.com/a/42832469

PIDS=$(fps "$1" | xargs)
KILL_ARGS="${@:2:99}"

if [[ -n "${PIDS}" ]]; then
    echo "Running: kill ${KILL_ARGS} ${PIDS}..."
    echo ${PIDS} | xargs kill "${KILL_ARGS}"
fi
