#!/bin/bash
THINGS="Commands|cmds
Manuals in WWW Browser|bman
Manuals|fman
Terminal in an Specific Session|t
Terminal|x-terminal-emulator
WWW Browser in an Specific Profile|xwp
WWW Browser|xw
X Applications|xcmds
"

COMMAND=$(echo "${THINGS}" | fzf | cut -d'|' -f2)

if [[ -n ${COMMAND} ]]; then
    /bin/bash -i -c "${COMMAND}"
fi
