#!/bin/bash
THINGS="\
Commands                            | cmds
Manuals                             | fman
Manuals in WWW Browser              | bman
Python Shell                        | bpython
Terminal                            | x-terminal-emulator &
Terminal - Root                     | gksu /usr/bin/x-terminal-emulator &
Terminal - Specific Session         | t
WWW Browser                         | xw
WWW Browser - Icongnito             | xwi
WWW Browser - Specific Profile      | xwp
X Applications                      | xcmds\
"

QUERY="$@"
COMMAND=$(echo "${THINGS}" | fzf --query="${QUERY}" | cut -d'|' -f2 | xargs)

if [[ -n ${COMMAND} ]]; then
    /bin/bash -i -c "${COMMAND}"
fi
