#!/bin/bash
set -euo pipefail

USAGE='rsync.sh <source> <dest> [<rsync_opts>...]'

function die() {
    echo "$*" 1>&2
    exit 1
}

DEFAULT_OPTS="--recursive --modify-window=10 --links --perms --times --one-file-system --delete --progress --verbose --human-readable"

SOURCE=${1:-}
DEST=${2:-}


if [[ -z ${SOURCE} || -z ${DEST} ]]; then
    die ${USAGE}
fi

if [[ ! -e ${SOURCE} ]]; then
    die "Source does not exists: ${SOURCE}"
fi


rsync ${DEFAULT_OPTS} "${@:3}" "${SOURCE}" "${DEST}"
