#!/bin/bash
APPS_DIR="/usr/share/applications"
CMDS=$(ls ${APPS_DIR}/*.desktop | xargs -n1 basename --suffix=.desktop | sort --unique)
CMD=$(echo "${CMDS}" | fzf)
if [[ -n ${CMD} ]]; then
    "${CMD}" &
fi
