#!/bin/bash
# Usage: xwp
# Open web browser using an specific profile.
CONFIG="${HOME}/.config/google-chrome/Local State"
QUERY='.profile.info_cache | to_entries[] | [.value.name, .value.gaia_name, .key] | join(" | ")'
PROFILES=$(jq -r "${QUERY}" "${CONFIG}" | sort)
PROFILE=$(echo "${PROFILES}" | fzf --query=${1} --select-1 | cut -d"|" -f3 | xargs)  # Use xargs to trim whitespaces.
if [[ -n "${PROFILE}" ]]; then
    /usr/bin/x-www-browser --profile-directory="$PROFILE" 2> /dev/null &
fi
